# Default configuration
cockroachdb:
  # See https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml
  image:
    repository: cockroachdb/cockroach
  fullnameOverride: dss-cockroachdb
  tls:
    certs:
      provided: true
      nodeSecret: cockroachdb.node
      clientRootSecret: cockroachdb.client.root
      selfSigner:
        enabled: false
  ingress:
    enabled: false

loadBalancers:
  cockroachdbNodes:
    - ip: 192.168.0.21
#      subnet: subnet-xxx # for aws only
    - ip: 192.168.0.22
#      subnet: subnet-xxx # for aws only
    - ip: 192.168.0.23
#      subnet: subnet-xxx # for aws only 

dss:
  image: docker.io/interuss/dss:v0.15.0 # See https://hub.docker.com/r/interuss/dss/tags for official image releases.
  conf:
    pubKeys:
      - /test-certs/auth2.pem
    jwksEndpoint: ''
    jwksKeyIds: []
    hostname: dss.example.com
    enableScd: true

global:
  cloudProvider: azure-asl 